Using /etc/ansible/ansible.cfg as config file

PLAY [Ensure re-authentication for privilege escalation is not disabled globally] ***

TASK [Gathering Facts] *********************************************************
ok: [192.168.73.142]

TASK [Check if re-authentication for privilege escalation is disabled] *********
ok: [192.168.73.142] => changed=false 
  cmd: grep -E '^\s*Defaults\s+!authenticate' /etc/sudoers /etc/sudoers.d/*
  delta: '0:00:00.007343'
  end: '2023-06-21 21:46:33.237819'
  failed_when_result: false
  msg: ''
  rc: 0
  start: '2023-06-21 21:46:33.230476'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    /etc/sudoers:Defaults !authenticate
    /etc/sudoers.d/ansible:Defaults !authenticate
  stdout_lines: <omitted>

TASK [Enable re-authentication for privilege escalation] ***********************
fatal: [192.168.73.142]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'path'. 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'path'
  
    The error appears to be in '/home/mario/Documents/tfm/use-cases-ansible-GPT/use-cases/rhel8/playbooks/case3/test_case3_LD_rhel8.yml': line 15, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: Enable re-authentication for privilege escalation
          ^ here

PLAY RECAP *********************************************************************
192.168.73.142             : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Playbook run took 0 days, 0 hours, 0 minutes, 17 seconds
